apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: titan
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "get", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
  # rhea needs to watch cedar policy config maps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  # legacy CRs
  - apiGroups: ["junovfx.com"]
    resources: ["groups", "users"]
    verbs: ["list", "create", "delete", "get", "patch", "update"]
  # target CRs
  - apiGroups: ["juno-innovations.com"]
    resources: ["groups", "users"]
    verbs: ["list", "create", "delete", "get", "patch", "update"]
