apiVersion: v1
kind: Service
metadata:
  name: genesis
  namespace: {{ .Release.Namespace }}
  {{- if .Values.warp.enabled }}
  labels:
    internal-cks.conductor.technology/warp: "true"
  annotations:
    internal-cks.conductor.technology/warp-hostname: {{ .Values.warp.hostname | quote }}
  {{- end }}
spec:
  selector:
    app: genesis
  ports:
    {{- if .Values.tls.enabled }}
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    {{- end }}
    - port: {{ .Values.ports.ui }}
      targetPort: {{ .Values.ports.ui }}
      protocol: TCP
      name: frontend
    - port: {{ .Values.ports.backend }}
      targetPort: {{ .Values.ports.backend }}
      protocol: TCP
      name: backend
